@startuml
title <b>XiaDxp - Diagram Sequence  : SaveConfig - 2015/09/15</b>\n**********************************************
actor User

participant "Device" as Device
box "VIEW" #LightGreen
	participant Device
end box

participant "Controller" as Ctrl
box "       CONTROLLER      " #Orange
	participant Ctrl
end box

participant "Acquisition" as Acq
participant "DriverHelper" as Driver
box "MODEL" #LightBlue
	participant Acq
	participant Driver
end box

User -> Device: SaveConfig(alias)
activate Device

Device -> Ctrl: save_config(file_name)
activate Ctrl


Ctrl -> Acq : save_config(file_name)
activate Acq

Acq -> Driver : save_config(file_name)
activate Driver

Driver --> Acq
deactivate Driver

note right 
        Driver library save all modified parameters in the the *.ini
        Parameters can be modified by user through tango attributes
        This operation takes <1 second
end note

Acq --> Ctrl : 
deactivate Acq

Ctrl --> Device : 
deactivate Ctrl

deactivate Device

@enduml