@startuml
title <b>XiaDxp - Diagram State - 2015/09/15</b>\n**********************************************
scale 600 width
skinparam backgroundColor LightYellow
skinparam state {
    StartColor Black
    EndColor Black
    BackgroundColor Peru
    BackgroundColor<<Standby>> Yellow
    BackgroundColor<<Fault>> Red
    BackgroundColor<<Running>> Green
    BackgroundColor<<Calibrating>> Purple
    BorderColor Gray
    FontName Arial
}


[*] -> Init
Init : do/Load_Config_File(memorizedAlias)
Init --> Calibrating <<Calibrating>> : [Succeeded]
Init --> Fault <<Fault>> : [Failed]

Calibrating : do/xiaInit("file.ini")
Calibrating : do/xiaStartSystem()
Calibrating --> Standby <<Standby>> : [Succeeded]
Calibrating --> Fault : [Failed]

Standby --> Running <<Running>> : Start

state Running <<Running>>{
  state "Acquisition Task Periodic" as acquiring <<Running>>
  acquiring : entry/collect_data()
  acquiring : do/store_statistics
  acquiring : do/store_datas
  [*] --> acquiring  
  acquiring --> acquiring : [Xia board is runnig]
}

Running --> Standby : ![Xia board is running] / Stop
Running --> Fault : [Failed]


Fault -->[*]
 
@enduml

@enduml