static const char *RcsId = "$Id $";
//+=============================================================================
//
// file :         XiaDxpStateMachine.cpp
//
// description :  C++ source for the XiaDxp and its alowed 
//                methods for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <XiaDxp.h>
#include <XiaDxpClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace XiaDxp_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_nbModules_allowed
// 
// description : 	Read/Write allowed for nbModules attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_nbModules_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::DISABLE	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ((get_state()==Tango::RUNNING)&& type==Tango::READ_REQ )
		{
           return true;
		}
             
        
//		if ( (get_state()==Tango::FAULT && is_device_initialized())&& type==Tango::READ_REQ )
//		{	
//           return true;
//		}
        
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_nbChannels_allowed
// 
// description : 	Read/Write allowed for nbChannels attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_nbChannels_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::DISABLE	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ((get_state()==Tango::RUNNING)&& type==Tango::READ_REQ )
		{
           return true;
		}
             
        
//		if ( (get_state()==Tango::FAULT && is_device_initialized())&& type==Tango::READ_REQ )
//		{	
//           return true;
//		}
        
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_currentConfigFile_allowed
// 
// description : 	Read/Write allowed for currentConfigFile attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_currentConfigFile_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::DISABLE	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_currentMode_allowed
// 
// description : 	Read/Write allowed for currentMode attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_currentMode_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::DISABLE	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_currentAlias_allowed
// 
// description : 	Read/Write allowed for currentAlias attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_currentAlias_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::DISABLE	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_nbBins_allowed
// 
// description : 	Read/Write allowed for nbBins attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_nbBins_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::DISABLE	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ((get_state()==Tango::RUNNING)&& type==Tango::READ_REQ )
		{
           return true;
		}
             
        
//		if ( (get_state()==Tango::FAULT && is_device_initialized())&& type==Tango::READ_REQ )
//		{	
//           return true;
//		}
        
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}


//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_streamTargetPath_allowed
// 
// description : 	Read/Write allowed for streamTargetPath attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_streamTargetPath_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::DISABLE)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_streamType_allowed
// 
// description : 	Read/Write allowed for streamType attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_streamType_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::DISABLE)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_streamTargetFile_allowed
// 
// description : 	Read/Write allowed for streamTargetFile attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_streamTargetFile_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::DISABLE)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_streamNbDataPerAcq_allowed
// 
// description : 	Read/Write allowed for streamNbDataPerAcq attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_streamNbDataPerAcq_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::DISABLE)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_streamNbAcqPerFile_allowed
// 
// description : 	Read/Write allowed for streamNbAcqPerFile attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_streamNbAcqPerFile_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::DISABLE)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_peakingTime_allowed
// 
// description : 	Read/Write allowed for peakingTime attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_peakingTime_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::DISABLE	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ((get_state()==Tango::RUNNING)&& type==Tango::READ_REQ )
		{
           return true;
		}
             
        
//		if ( (get_state()==Tango::FAULT && is_device_initialized())&& type==Tango::READ_REQ )
//		{	
//           return true;
//		}
        
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_dynamicRange_allowed
// 
// description : 	Read/Write allowed for dynamicRange attribute.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_dynamicRange_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::DISABLE	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ((get_state()==Tango::RUNNING)&& type==Tango::READ_REQ )
		{
           return true;
		}
             
        
//		if ( (get_state()==Tango::FAULT && is_device_initialized())&& type==Tango::READ_REQ )
//		{	
//           return true;
//		}
        
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_LoadConfigFile_allowed
// 
// description : 	Execution allowed for LoadConfigFile command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_LoadConfigFile_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_Stop_allowed
// 
// description : 	Execution allowed for Stop command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_Stop_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ( get_state()==Tango::FAULT && is_device_initialized())
		{	
           return true;
		}
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_SaveConfigFile_allowed
// 
// description : 	Execution allowed for SaveConfigFile command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_SaveConfigFile_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ( get_state()==Tango::FAULT && is_device_initialized())
		{	
           return true;
		}
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_Snap_allowed
// 
// description : 	Execution allowed for Snap command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_Snap_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ( get_state()==Tango::FAULT && is_device_initialized())
		{	
           return true;
		}
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_RemoveRois_allowed
// 
// description : 	Execution allowed for RemoveRois command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_RemoveRois_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ( get_state()==Tango::FAULT && is_device_initialized())
		{	
           return true;
		}
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_SetRoisFromFile_allowed
// 
// description : 	Execution allowed for SetRoisFromFile command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_SetRoisFromFile_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ( get_state()==Tango::FAULT && is_device_initialized())
		{	
           return true;
		}
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_SetRoisFromList_allowed
// 
// description : 	Execution allowed for SetRoisFromList command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_SetRoisFromList_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ( get_state()==Tango::FAULT && is_device_initialized())
		{	
           return true;
		}
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_GetRois_allowed
// 
// description : 	Execution allowed for GetRois command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_GetRois_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code
		if ( get_state()==Tango::FAULT && is_device_initialized())
		{	
           return true;
		}
		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		XiaDxp::is_StreamResetIndex_allowed
// 
// description : 	Execution allowed for StreamResetIndex command.
//
//-----------------------------------------------------------------------------
bool XiaDxp::is_StreamResetIndex_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT	||
		get_state() == Tango::INIT	||
		get_state() == Tango::RUNNING	||
		get_state() == Tango::OFF)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}

}	// namespace XiaDxp_ns
